module.exports = {
  branches: ["main", "build"],
  plugins: [
    "@semantic-release/commit-analyzer",
    [
      '@semantic-release/release-notes-generator',
      {
          preset: "conventionalcommits",
          presetConfig: {
              commitUrlFormat: "{{host}}/{{owner}}/_apis/git/repositories/{{repository}}/diffs/commits?baseVersionType=tag&baseVersion={{previousTag}}&targetVersionType=tag&targetVersion={{currentTag}}&api-version=7.0",
              compareUrlFormat: "{{host}}/{{owner}}/{{repository}}/branchCompare?baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}&_a=files"
          },
          parserOpts: {
              noteKeywords: ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
          }
      }
    ],
    [
      "@semantic-release/changelog",
      {
        changelogFile: "CHANGELOG.md",
        changelogTitle:
          "# Changelog\n**Please Note: This file is automatically generated by the *semantic-release* tool. DO NOT make any manual modifications**\n\nAll notable changes to this project will be documented in this file. See [semantic-release](https://github.com/semantic-release/semantic-release) for commit guidelines.",
      },
    ],
    [
      "@semantic-release/npm",
      {
        npmPublish: false,
      },
    ],
    [
      "@semantic-release/git",
      {
        message: "chore(release): Upgrade from ${lastRelease.version} to ${nextRelease.version} on <%= new Date().toLocaleDateString('en-US', {year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }) %> [skip ci]\n\n${nextRelease.notes}",
      },
    ],
  ],
  tagFormat: "v${version}",
  compareUrlFormat: "{{host}}/{{owner}}/{{repository}}/branchCompare?baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}&_a=files"
};
