// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WebScraperFileDownloadEvent
    {
        [JsonProperty("eventId")]
        public string EventId { get; set; }

        [JsonProperty("websiteurl")]
        public Uri Websiteurl { get; set; }

        [JsonProperty("xpath")]
        public string Xpath { get; set; }

        [JsonProperty("fullxpath")]
        public string Fullxpath { get; set; }

        [JsonProperty("filePrefixPattern")]
        public string FilePrefixPattern { get; set; }
    }
}
